version: '3.8'
services:
  pacilkrep:
    image: itzg/minecraft-server:java17-graalvm-ce
    container_name: pacilkrep
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.19.2"
      TZ: "Asia/Jakarta"
      CONSOLE: "FALSE"
      STOP_SERVER_ANNOUNCE_DELAY: 30
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      
      MEMORY: "${MEMORY:-6G}"
      JVM_DD_OPTS: "disable.watchdog:TRUE" #Paper
      USE_AIKAR_FLAGS: "TRUE"
      ENABLE_ROLLING_LOGS: "TRUE"
      STOP_DURATION: 300
      USE_SIMD_FLAGS: "TRUE"
      LOG_TIMESTAMP: "TRUE"

      SERVER_NAME: "PacilCraft"
      MAX_TICK_TIME: "-1" #For autopause to work
      MOTD: "Welcome to pacilcraft!"
      DIFFICULTY: "hard"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "${RCON_PASSWORD:-pacilkrep}"
      MAX_PLAYERS: 100
      ENABLE_COMMAND_BLOCK: "TRUE"
      ONLINE_MODE: "FALSE"
      SPAWN_PROTECTION: 16

      #DiceFurniture,Dynmap,Furnlib-Protectionlib,gsit,luckperms,multiverse,nexauth,plugmanx,durability,clearlagg,CoordinatesHud,Graves,Vault,armor-stand-editor,jobs-reborn,CMILib,PlaceholderAPI,LuckPermsChat,PAPIConditional
      SPIGET_RESOURCES: "6006,274,9368,62325,28140,390,88015,88135,74166,68271,69915,74208,34315,94503,4216,87610,6245,68965,82920" 
      MODS: >-
        /extras/mods,
        https://dev.bukkit.org/projects/drivebackupv2/files/latest,
        https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar,
        https://dev.bukkit.org/projects/worldguard/files/latest,
        https://dev.bukkit.org/projects/beaconwaypoints/files/latest,
        https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/lastSuccessfulBuild/artifact/build/libs/SkinsRestorer.jar,
        https://dev.bukkit.org/projects/orebfuscator-anti-x-ray/files/latest,
        https://dev.bukkit.org/projects/signshop/files/latest,
        https://ci.codemc.io/job/Updated-NoCheatPlus/job/Updated-NoCheatPlus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar,
        https://dev.bukkit.org/projects/crackshot/files/latest,
        https://github.com/nulli0n/NexEngine-spigot/releases/latest/download/NexEngine.jar,
        
        https://github.com/MyPetORG/MyPet/releases/download/3.12-SNAPSHOT-B1725/MyPet-3.12-SNAPSHOT-B1725.jar,
        https://github.com/EssentialsX/Essentials/releases/latest/download/EssentialsX-2.19.7.jar,
        https://github.com/EssentialsX/Essentials/releases/latest/download/EssentialsXSpawn-2.19.7.jar,
        https://github.com/XZot1K/SimplePortals/releases/latest/download/SimplePortals-1.7.1.jar,
        https://ci.athion.net/job/FastAsyncWorldEdit/lastStableBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.4.9-SNAPSHOT-294.jar,
        https://zrips.net/Residence/files/Residence5.0.3.0.jar,
      VANILLATWEAKS_FILE: /extras/vanillatweaks/datapacks.json,/extras/vanillatweaks/tweaks.json,/extras/vanillatweaks/resourcepacks.json
      REMOVE_OLD_VANILLATWEAKS: "TRUE"
      RESOURCE_PACK: "https://raw.githubusercontent.com/dirtboll/pacilcraft/master/resourcepack.zip"
      RESOURCE_PACK_SHA1: 5c89c3e27015ba711c4f131bcf74e7d4c96e77d1
      DATAPACKS: >-
        /extras/datapacks/Trumpet-Skeleton-[datapack]-v1.0.0.zip

      # RCON_CMDS_STARTUP: |-
      #   iris pregen start 1000 world=otherworld
      # RCON_CMDS_LAST_DISCONNECT: |-
      #   iris pregen start 1000 world=otherworld
      # RCON_CMDS_FIRST_CONNECT: |-
      #   iris pregen stop
    ports:
      - "${PORT_MC:-25565}:25565"
      - "${PORT_DYNMAP:-8123}:8123"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./data:/data
      - ./extras:/extras
    tty: TRUE
    stdin_open: TRUE
    restart: unless-stopped
